INSERT INTO organizations (NAME)
VALUES ('HR');

INSERT INTO organizations (NAME)
VALUES ('FINANCE');

INSERT INTO customers (NAME, ORGANIZATION_NAME)
VALUES ('CUSTOMER1', 'HR');

INSERT INTO customers (NAME, ORGANIZATION_NAME)
VALUES ('CUSTOMER2', 'HR');

INSERT INTO customers (NAME, ORGANIZATION_NAME)
VALUES ('CUSTOMER_FINC', 'FINANCE');
